


"""
Practice 1
"""

number1_longNameOfVariable_longNameOfVariable = 20
number2_longNameOfVariable_longNameOfVariable = 2
print(number1_longNameOfVariable_longNameOfVariable+number2_longNameOfVariable_longNameOfVariable)
print(number1_longNameOfVariable_longNameOfVariable-number2_longNameOfVariable_longNameOfVariable)
print(number1_longNameOfVariable_longNameOfVariable*number2_longNameOfVariable_longNameOfVariable)
print(number1_longNameOfVariable_longNameOfVariable/number2_longNameOfVariable_longNameOfVariable)
print(number1_longNameOfVariable_longNameOfVariable%number2_longNameOfVariable_longNameOfVariable)
print(number1_longNameOfVariable_longNameOfVariable**number2_longNameOfVariable_longNameOfVariable)
print(number1_longNameOfVariable_longNameOfVariable//number2_longNameOfVariable_longNameOfVariable)

